### PR TITLE
Update android.m3u

### PR DESCRIPTION
**Pull request by paulxgr2020**
ANT1 added

### CODE REVIEW

**Comment by komhsgr** [comment]
https://antennaamdnoenc.akamaized.net/ant1_akamai/abr/playlist.m3u8  not working in mx player have firewall try it

**Comment by komhsgr** [comment]
https://skai-live-back.siliconweb.com/media/cambria4/index.m3u8
problems with geo lock and problems some times link down

**Comment by FPSUsername** [comment]
> https://antennaamdnoenc.akamaized.net/ant1_akamai/abr/playlist.m3u8 not working in mx player have firewall try it

I can confirm that it works outside of Greece without a VPN, but the stream doesn't work 24/7 reliably. It would be nice to still have it in the list.

**Comment by komhsgr** [comment]
if they dont work why but in list?  to take 1 star and say ant1 not working ant1 not working?

**Comment by FPSUsername** [comment]
Just leave a note then?
It works most of the times, to watch series they have on, so I don't see an issue when it cuts out. It often cuts out on the commercials (but do people really sit there watching commercials?)

**Comment by georgoskar** [comment]
#EXTINF:-0 tvg-id="ext" group-title="channels",baraza FHD greek music hits
https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8
#EXTINF:-1 tvg-id="ext" group-title="channels",baraza FHD greek 2
https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8
#EXTINF:-1 tvg-id="ext" group-title="channels",Baraza Relaxing music
https://media2.streambrothers.com:1936/8106/8106/playlist.m3u8

**Comment by komhsgr** [comment]
και σε λιγες ωρες Βεργινα, Blue sky, one tv, art tv κτλ κτλ θα είναι down.   Kαι επισης ποιο βλέπει Αμερικάνικα κανάλια και stream links  απο pluto tv

**Pull request closed without merging**
